Test travis
threefoldtecharchive/jumpscaleX_archived pull request #140
Opened 2019-01-23 15:50 UTC by Dina-Abd-Elrahman

add  travis nightly job for builders

https://github.com/threefoldtech/jumpscaleX/issues/138

2019-01-24 07:52 UTC, zaibon requested changes
Please remove all .pyc files and put back the gitignore file

2019-01-24 07:52 UTC, zaibon commented on .gitignore
> -# Byte-compiled / optimized / DLL files
Why is this removed?

2019-01-24 07:52 UTC, zaibon commented on .travis.yml
> +  - test_travis
Does this mean you want to run the test only for this branch? If yes, why?

2019-01-24 07:52 UTC, zaibon commented on .vscode/settings.json
> +{
This file should not be part of this PR. Please remove. You can even add this to the gitignore to make sure nobody will push these files anymore

2019-01-27 10:01 UTC, Dina-Abd-Elrahman commented
Okay
Sorry my bad 
I will fix this part and push again

2019-02-14 16:16 UTC, closed without merging