Config fixes in clients
threefoldtecharchive/jumpscaleX_archived pull request #87
Opened 2018-12-24 10:33 UTC by ranatrk

#### What this PR resolves:
- Updates in clients and factories related to config

#### Changes proposed in this PR:

- make sure **j.application.JSBASEConfig** and **j.application.JSFactoryBaseClass** are used
- make sure of _init(self) in factories
- make sure of _init_new(self) in clients
- use of SCHEMATEXT
- move __jslocation__ out of init
- add _CHILDCLASS
- use of **self.[x]** instead of **self.config.data['x']**

**Fixes**: #4

2018-12-24 11:38 UTC, BolaNasr commented on Jumpscale/clients/etcd/EtcdClient.py
> +    port = 2379 (I)
we need type ```ipport``` not integer

2018-12-24 11:38 UTC, BolaNasr commented on Jumpscale/clients/syncthing/SyncthingClient.py
> +    sshport = 22 (I)
we need type ipport not integer in (port and sshport)

2018-12-24 11:38 UTC, BolaNasr commented on Jumpscale/clients/gitea/GiteaFactory.py
> +    # def _init(self):
need to remove this comment line

2018-12-25 08:57 UTC, serboctor requested changes
Part of the cleanup is to add docstrings, tests and change anything in the syntax that doesn't follow the repo conventions for any module we work on. None of that is done in the PR. 
If it is not going to be part of this PR, are there tasks created specifically for these modules?

2018-12-25 12:27 UTC, BolaNasr commented
@serboctor 
This PR isn't for cleaning up it just makes the clients work with the new config manager , after we are sure all clients works Good , we will cleanup all .

2018-12-27 08:52 UTC, BolaNasr reviewed
@ranatrk  please fix conflict in files

2018-12-27 08:52 UTC, BolaNasr commented on Jumpscale/clients/s3/S3Client.py
> +    port = 9000 (I)
should add type ipport not int

2018-12-27 08:52 UTC, BolaNasr commented on Jumpscale/clients/sshagent/SSHAgent.py
> +                echo {self.passphrase} | SSH_ASKPASS=./ap-cat.sh ssh-add -t {duration} {path}
change path to self.path

2018-12-30 16:01 UTC, serboctor requested changes

2018-12-30 16:01 UTC, serboctor commented on Jumpscale/clients/intercom/IntercomClient.py
> +        return None
No new line at the end of the file

2018-12-30 16:01 UTC, serboctor commented on Jumpscale/clients/postgresql/PostgresqlClient.py
> +    def peewee_client_get(self):
if this isnt referenced anywhere, can you remove it?

2018-12-30 16:01 UTC, serboctor commented on Jumpscale/clients/postgresql/PostgresqlFactory.py
> +        @param db: db name to be created
these docs dont match the one in the contribution guidelines, we use `:` not `@`. Check the example in the readme and modify this and the docs below too, please.

2018-12-30 16:01 UTC, serboctor commented on Jumpscale/clients/zdb/ZDBAdminClient.py
> +            import ipdb
remove this please

2018-12-30 16:01 UTC, serboctor commented on Jumpscale/sal/hostfile/HostFile.py
> -
this shouldnt be removed...I thinked you messed up something while merging

2018-12-31 11:49 UTC, serboctor approved these changes

2018-12-31 11:49 UTC, merged